### PR TITLE
Update album.py

### PR DESCRIPTION
**Pull request by isakbosman**
Fix request url as it returns 404. Correct url can be reviewed here: https://developer.spotify.com/console/get-artist-albums/

### CODE REVIEW

**Review by jingming — APPROVED** [review]
Looks great! I'll try to get this published ASAP.

**Comment by isakbosman** [comment]
Sounds good! Thanks

**Comment by jingming** [comment]
@geekonedge thanks for the contributions! However, you should separate out these into separate PRs so it's easier to break up.

**Comment by isakbosman** [comment]
Ah I was planning to do that and forgot the PR is still open. Woops. Closing now :)

**Pull request closed without merging**
